# Redirige HTTP → HTTPS
server {
  listen 80;
  server_name pld.legalflow.solutions;

  location /.well-known/acme-challenge/ {
    root /var/www/public;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

# HTTPS
server {
  listen 443 ssl;
  server_name pld.legalflow.solutions;
  index index.php index.html;
  root /var/www/public;

  ssl_certificate     /etc/letsencrypt/live/pld.legalflow.solutions/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/pld.legalflow.solutions/privkey.pem;
  ssl_protocols       TLSv1.2 TLSv1.3;
  ssl_ciphers         HIGH:!aNULL:!MD5;

  client_max_body_size 100M;

  location / {
    root /var/www/public;
    index index.html index.php;
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass php_automatizacion:9000;
    fastcgi_read_timeout 3600;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    send_timeout 3600;
    proxy_connect_timeout 3600;
    proxy_read_timeout    3600;
    proxy_send_timeout    3600;
  }
}
