

; Example

; [Date]
; date.timezone = "Asia/Tokyo"

; [mbstring]
; mbstring.language = Japanese
memory_limit=-1
post_max_size=4G
upload_max_filesize=4G
max_file_uploads=20
output_buffering=4096
max_execution_time=30000